### PR TITLE
Update app.json

### PR DESCRIPTION
**Pull request by Goobermas**
Fix Heroku from blocking you from deploying. (Hopefully)

### CODE REVIEW

**Comment by Goobermas** [comment]
Well it allows me to deploy but, it doesn't fully deploy

```sh
Step 5/9 : ADD ./webapp /root/webapp/
failed to export image: failed to create image: failed to get layer sha256:0cceea29c5968cc5b75f00168bb3274c45841ce9c56e05162ce8b0857b7fdfa2: layer does not exist
```

**Comment by enwaiax** [comment]
Actually Heroku will remove free resource in future. Try other SAAS platform, for example https://app.koyeb.com/

**Comment by Goobermas** [comment]
I'm aware of them removing the free tier later this month, but you can still use whats left of this month then find a new platform.

**Comment by enwaiax** [comment]
> I'm aware of them removing the free tier later this month, but you can still use whats left of this month then find a new platform.

Yes, I have updated. Check the README for alternatives.

**Pull request closed without merging**
